#!/usr/bin/env bash

# Commands that should be applied only for interactive shells.
[[ $- == *i* ]] || return

function source_if_exists() {
    [ -f "$1" ] && source "$1"
}

source_if_exists /etc/bashrc

HISTFILESIZE=2000
HISTSIZE=1000

shopt -s checkwinsize
shopt -s histappend
shopt -s histreedit
shopt -s hostcomplete

export PROMPT_COMMAND="${PROMPT_COMMAND:+$PROMPT_COMMAND$"\n"}history -a; history -c; history -r"
#HISTTIMEFORMAT='%F %T '

# Set no limit for history file size
HISTFILESIZE=-1		# no limits

# Set no limit for history file size
HISTSIZE=-1

# Do not store a duplicate of the last entered command
HISTCONTROL=ignoredups

function cover() {
    local t="/tmp/go-cover.$$.tmp"
    go test -coverprofile=$t "$@" && go tool cover -html=$t && unlink $t
}

if [ "$TERM" != "dumb" ]; then
    source_if_exists /usr/share/fzf/shell/key-bindings.bash
fi

unset PROMPT_COMMAND

vterm_printf() {
    if [ -n "$TMUX" ] && ( [ "${TERM%%-*}" = "tmux" ] || [ "${TERM%%-*}" = "screen" ] ); then
	printf "\ePtmux;\e\e]%s\007\e\\" "$1";
    else
	if [ "${TERM%%-*}" = "screen" ]; then
	    printf "\eP\e]%s\007\e\\" "$1";
	else
	    printf "\e]%s\e\\" "$1";
	fi;
    fi
}

if [[ "$INSIDE_EMACS" = 'vterm' ]]; then
    function clear () {
	vterm_printf "51;Evterm-clear-scrollback";
	tput clear
    }
fi

random_macaddr() {
    # https://serverfault.com/questions/299556/how-to-generate-a-random-mac-address-from-the-linux-command-line
    openssl rand -hex 6 | sed 's/\(..\)/\1:/g; s/:$//'
}

source_if_exists ~/.bash_aliases

if which direnv >/dev/null 2>&1; then
    eval "$(direnv hook bash)"
fi

