#!/bin/bash

set -ex

dconf write /org/gnome/desktop/interface/text-scaling-factor 1.25

# Emacs everywhere!
dconf write /org/gnome/desktop/interface/gtk-key-theme "'Emacs'"

# Terminal
# dconf write /org/gnome/Terminal/Legacy/Settings/menu-accelerator-enabled false
# dconf write /org/gnome/Terminal/Legacy/Settings/default-show-menubar false

# Desktop
dconf write /org/gnome/desktop/interface/clock-show-date true
dconf write /org/gnome/desktop/privacy/show-full-name-in-top-bar false

# Nautilus
dconf write /org/gnome/nautilus/preferences/sort-directories-first true

# Caps Lock, Alt, Win, et al.
dconf write /org/gnome/desktop/input-sources/xkb-options "['caps:ctrl_modifier', 'altwin:swap_alt_win']"

# Mouse and Touchpad
dconf write /org/gnome/settings-daemon/peripherals/touchpad/tap-to-click false
dconf write /org/gnome/settings-daemon/peripherals/touchpad/natural-scroll true

# Compiz
dconf write /org/compiz/profiles/unity/plugins/unityshell/icon-size 16
dconf write /org/compiz/profiles/unity/plugins/core/active-plugins "['core', 'composite', 'opengl', 'compiztoolbox', 'decor', 'commands', 'place', 'mousepoll', 'wall', 'session', 'regex', 'grid', 'move', 'animation', 'resize', 'copytex', 'workarounds', 'neg', 'snap', 'gnomecompat', 'imgpng', 'vpswitch', 'fade', 'unitymtgrabhandles', 'expo', 'scale', 'ezoom', 'unityshell']"
dconf write /org/compiz/profiles/unity/plugins/neg/screen-toggle-key "'<Shift><Control><Super>m'"

# Terminal
dconf write /org/gnome/desktop/interface/cursor-blink false

# Power Management
dconf write /com/canonical/indicator/power/show-time true
