#!/bin/sh

#echo 2 | sudo tee -a /sys/module/hid_apple/parameters/fnmode
echo options hid_apple fnmode=2 | sudo tee -a /etc/modprobe.d/hid_apple.conf
sudo update-initramfs -u -k all
echo 0 | sudo tee -a /sys/module/hid_apple/parameters/iso_layout
