#!/bin/sh
#
# clean-emacs-files: Invoke clean-files with an expression that selects
#	files that end in "~" or start and end with "#".
#
# George Ferguson, ferguson@cs.rochester.edu, 23 Aug 1991.
#

CLEAN_FILES_CALLER="$0"
export CLEAN_FILES_CALLER
exec clean-files '/~$/ || /^#.*#$/' "$@"
