#!/bin/bash

set -eu

if [ $# -lt 1 ]; then
    echo "usage: ${0##*/} <org-name>"
    exit 1
fi

mkdir -p $1 && cd $1

curl -s https://api.github.com/orgs/"$1"/repos?per_page=200 | \
    ruby -rubygems -e 'require "json"; JSON.load(STDIN.read).each { |repo| %x[git clone #{repo["ssh_url"]} ]}'
