# -*-shell-script-*-

alias amke=make
alias mkae=make
alias h='history 10'
alias lst='ls -trl | tail'
alias more=less
alias fmv8=/opt/arm/Foundation_v8pkg/models/Linux64_GCC-4.1/Foundation_v8
# Courtesy of kergoth in IRC
alias bbag="ag -G '\.(bb|bbappend|inc|conf)\$'"
alias g=git
